// <auto-generated />
using System;
using Bielu.Microservices.Orchestrator.Storage.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bielu.Microservices.Orchestrator.Examples.Api.Migrations
{
    [DbContext(typeof(InstanceStoreDbContext))]
    [Migration("20260430064526_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bielu.Microservices.Orchestrator.Storage.EfCore.ManagedInstanceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ContainerIdsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ContainerIds");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DesiredReplicas")
                        .HasColumnType("integer");

                    b.Property<string>("DesiredState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<Guid>("OrchestratorId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalRequestJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OriginalRequest");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ManagedInstances", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
